# LASSO with coordinate descent

In this notebook, you will implement your very own LASSO solver via coordinate descent. You will:
* Write a function to normalize features
* Implement coordinate descent for LASSO
* Explore effects of L1 penalty

Make sure you have the latest version of graphlab (>= 1.7)

In [45]:
import graphlab as gl
from graphlab import SFrame

In [46]:
sales = SFrame('../data/kc_house_data.csv')
# In the dataset, 'floors' was defined with type string, 
# so we'll convert them to int, before using it below
sales['floors'] = sales['floors'].astype(int) 

Finished parsing file /Users/tolo/Dropbox/Data/Studies/Informatics/ML Regression/assignments/data/kc_house_data.csv

Parsing completed. Parsed 100 lines in 0.112948 secs.

------------------------------------------------------
Inferred types from first line of file as 
column_type_hints=[int,str,float,int,float,int,int,float,int,int,int,int,int,int,int,int,int,float,float,int,int]
If parsing fails due to incorrect types, you can correct
the inferred type list above and pass it to read_csv in
the column_type_hints argument
------------------------------------------------------


Finished parsing file /Users/tolo/Dropbox/Data/Studies/Informatics/ML Regression/assignments/data/kc_house_data.csv

Parsing completed. Parsed 21613 lines in 0.084153 secs.

If we want to do any "feature engineering" like creating new features or adjusting existing ones we should do this directly using the SFrames as seen in the first notebook of Week 2. For this notebook, however, we will work with the existing features.

### Import useful functions from previous notebook

As in Week 2, we convert the SFrame into a 2D Numpy array. Copy and paste `get_num_data()` from the second notebook of Week 2.

In [47]:
import numpy as np

In [48]:
def get_numpy_data(data_sframe, features, label):
    data_sframe['intercept'] = 1
    features = ['intercept'] + features
    features_sframe = data_sframe[features]
    feature_matrix = features_sframe.to_numpy()
    label_sarray = data_sframe[label]
    label_array = label_sarray.to_numpy()
    return (feature_matrix, label_array)

Also, copy and paste the `predict_output()` function to compute the predictions for an entire matrix of features given the matrix and the weights:

In [49]:
def predict_output(feature_matrix, weights):
    return feature_matrix.dot(weights)

## Normalize features
In the house dataset, features vary wildly in their relative magnitude: `sqft_living` is very large overall compared to `bedrooms`, for instance. As a result, weight for `sqft_living` would be much smaller than weight for `bedrooms`. This is problematic because "small" weights are dropped first as `l1_penalty` goes up. 

To give equal considerations for all features, we need to **normalize features** as discussed in the lectures: we divide each feature by its 2-norm so that the transformed feature has norm 1.

Let's see how we can do this normalization easily with Numpy: let us first consider a small matrix.

In [50]:
X = np.array([[3.,5.,8.],[4.,12.,15.]])
print X

[[  3.   5.   8.]
 [  4.  12.  15.]]


Numpy provides a shorthand for computing 2-norms of each column:

In [14]:
norms = np.linalg.norm(X, axis=0) # gives [norm(X[:,0]), norm(X[:,1]), norm(X[:,2])]
print norms

[  5.  13.  17.]


To normalize, apply element-wise division:

In [15]:
print X / norms # gives [X[:,0]/norm(X[:,0]), X[:,1]/norm(X[:,1]), X[:,2]/norm(X[:,2])]

[[ 0.6         0.38461538  0.47058824]
 [ 0.8         0.92307692  0.88235294]]


Using the shorthand we just covered, write a short function called `normalize_features(feature_matrix)`, which normalizes columns of a given feature matrix. The function should return a pair `(normalized_features, norms)`, where the second item contains the norms of original features. As discussed in the lectures, we will use these norms to normalize the test data in the same way as we normalized the training data. 

In [17]:
def normalize_features(feature_matrix):
    norms = np.linalg.norm(feature_matrix, axis=0)
    return (feature_matrix/norms, norms)

To test the function, run the following:

In [18]:
features, norms = normalize_features(np.array([[3.,6.,9.],[4.,8.,12.]]))
print features
# should print
# [[ 0.6  0.6  0.6]
#  [ 0.8  0.8  0.8]]
print norms
# should print
# [5.  10.  15.]

[[ 0.6  0.6  0.6]
 [ 0.8  0.8  0.8]]
[  5.  10.  15.]


## Implementing Coordinate Descent with normalized features

We seek to obtain a sparse set of weights by minimizing the LASSO cost function
```
SUM[ (prediction - output)^2 ] + lambda*( |w[1]| + ... + |w[k]|).
```
(By convention, we do not include `w[0]` in the L1 penalty term. We never want to push the intercept to zero.)

The absolute value sign makes the cost function non-differentiable, so simple gradient descent is not viable (you would need to implement a method called subgradient descent). Instead, we will use **coordinate descent**: at each iteration, we will fix all weights but weight `i` and find the value of weight `i` that minimizes the objective. That is, we look for
```
argmin_{w[i]} [ SUM[ (prediction - output)^2 ] + lambda*( |w[1]| + ... + |w[k]|) ]
```
where all weights other than `w[i]` are held to be constant. We will optimize one `w[i]` at a time, circling through the weights multiple times.  
  1. Pick a coordinate `i`
  2. Compute `w[i]` that minimizes the cost function `SUM[ (prediction - output)^2 ] + lambda*( |w[1]| + ... + |w[k]|)`
  3. Repeat Steps 1 and 2 for all coordinates, multiple times

For this notebook, we use **cyclical coordinate descent with normalized features**, where we cycle through coordinates 0 to (d-1) in order, and assume the features were normalized as discussed above. The formula for optimizing each coordinate is as follows:
```
       ┌ (ro[i] + lambda/2)     if ro[i] < -lambda/2
w[i] = ├ 0                      if -lambda/2 <= ro[i] <= lambda/2
       └ (ro[i] - lambda/2)     if ro[i] > lambda/2
```
where
```
ro[i] = SUM[ [feature_i]*(output - prediction + w[i]*[feature_i]) ].
```

Note that we do not regularize the weight of the constant feature (intercept) `w[0]`, so, for this weight, the update is simply:
```
w[0] = ro[i]
```

## Effect of L1 penalty

Let us consider a simple model with 2 features:

In [227]:
simple_features = ['sqft_living', 'bedrooms']
my_output = 'price'
(simple_feature_matrix, output) = get_numpy_data(sales, simple_features, my_output)

Don't forget to normalize features:

In [228]:
simple_feature_matrix, norms = normalize_features(simple_feature_matrix)

We assign some random set of initial weights and inspect the values of `ro[i]`:

In [229]:
weights = np.array([1., 4., 1.])

Use `predict_output()` to make predictions on this data.

In [230]:
prediction = predict_output(simple_feature_matrix, weights)

Compute the values of `ro[i]` for each feature in this simple model, using the formula given above, using the formula:
```
ro[i] = SUM[ [feature_i]*(output - prediction + w[i]*[feature_i]) ]
```

*Hint: You can get a Numpy vector for feature_i using:*
```
simple_feature_matrix[:,i]
```

In [235]:
ro = [0 for i in range(len(weights))]
for i in range(len(weights)):
    ro[i] = simple_feature_matrix[:,i].dot(output - prediction + weights[i]*simple_feature_matrix[:,i])

In [236]:
["%.2g"%round(r) for r in ro]

['7.9e+07', '8.8e+07', '8.1e+07']

In [239]:
["%.2g" % (v/2) for v in [1.4e8, 1.64e8, 1.73e8, 1.9e8, 2.3e8]]

['7e+07', '8.2e+07', '8.6e+07', '9.5e+07', '1.2e+08']

***QUIZ QUESTION***

Recall that, whenever `ro[i]` falls between `-l1_penalty/2` and `l1_penalty/2`, the corresponding weight `w[i]` is sent to zero. Now suppose we were to take one step of coordinate descent on either feature 1 or feature 2. What range of values of `l1_penalty` **would not** set `w[1]` zero, but **would** set `w[2]` to zero, if we were to take a step in that coordinate? 

***QUIZ QUESTION***

What range of values of `l1_penalty` would set **both** `w[1]` and `w[2]` to zero, if we were to take a step in that coordinate? 

So we can say that `ro[i]` quantifies the significance of the i-th feature: the larger `ro[i]` is, the more likely it is for the i-th feature to be retained.

## Single Coordinate Descent Step

Using the formula above, implement coordinate descent that minimizes the cost function over a single feature i. Note that the intercept (weight 0) is not regularized. The function should accept feature matrix, output, current weights, l1 penalty, and index of feature to optimize over. The function should return new weight for feature i.

In [37]:
def lasso_coordinate_descent_step(i, feature_matrix, output, weights, l1_penalty):
    # compute prediction
    prediction = predict_output(feature_matrix, weights)
    # compute ro[i] = SUM[ [feature_i]*(output - prediction + weight[i]*[feature_i]) ]
    ro_i = feature_matrix[:,i].dot(output - prediction + weights[i]*feature_matrix[:,i])

    if i == 0: # intercept -- do not regularize
        new_weight_i = ro_i 
    elif ro_i < -l1_penalty/2.:
        new_weight_i = ro_i + l1_penalty/2
    elif ro_i > l1_penalty/2.:
        new_weight_i = ro_i - l1_penalty/2
    else:
        new_weight_i = 0.
    
    return new_weight_i

To test the function, run the following cell:

In [38]:
# should print 0.425558846691
import math
print lasso_coordinate_descent_step(1, np.array([[3./math.sqrt(13),1./math.sqrt(10)],[2./math.sqrt(13),3./math.sqrt(10)]]), 
                                   np.array([1., 1.]), np.array([1., 4.]), 0.1)

0.425558846691


## Cyclical coordinate descent 

Now that we have a function that optimizes the cost function over a single coordinate, let us implement cyclical coordinate descent where we optimize coordinates 0, 1, ..., (d-1) in order and repeat.

When do we know to stop? Each time we scan all the coordinates (features) once, we measure the change in weight for each coordinate. If no coordinate changes by more than a specified threshold, we stop.

For each iteration:
1. As you loop over features in order and perform coordinate descent, measure how much each coordinate changes.
2. After the loop, if the maximum change across all coordinates is falls below the tolerance, stop. Otherwise, go back to step 1.

Return weights

**IMPORTANT: when computing a new weight for coordinate i, make sure to incorporate the new weights for coordinates 0, 1, ..., i-1. One good way is to update your weights variable in-place. See following pseudocode for illustration.**
```
for i in range(len(weights)):
    old_weights_i = weights[i] # remember old value of weight[i], as it will be overwritten
    # the following line uses new values for weight[0], weight[1], ..., weight[i-1]
    #     and old values for weight[i], ..., weight[d-1]
    weights[i] = lasso_coordinate_descent_step(i, feature_matrix, output, weights, l1_penalty)
    
    # use old_weights_i to compute change in coordinate
    ...
```

In [240]:
def lasso_cyclical_coordinate_descent(feature_matrix, output, initial_weights, l1_penalty, tolerance=1.0):
    weights = initial_weights
    change = tolerance+1
    while change > tolerance:
        change = 0
        for i in range(len(weights)):
            old_weights_i = weights[i]
            weights[i] = lasso_coordinate_descent_step(
                i, feature_matrix, output, weights, l1_penalty)
            change = max(change, abs(old_weights_i - weights[i]))
    return weights.copy()

Using the following parameters, learn the weights on the sales dataset. 

In [241]:
simple_features = ['sqft_living', 'bedrooms']
my_output = 'price'
initial_weights = np.zeros(3)
l1_penalty = 1e7
tolerance = 1.0

First create a normalized version of the feature matrix, `normalized_simple_feature_matrix`

In [242]:
(simple_feature_matrix, output) = get_numpy_data(sales, simple_features, my_output)
(normalized_simple_feature_matrix, simple_norms) = normalize_features(simple_feature_matrix) 

Then, run your implementation of LASSO coordinate descent:

In [243]:
weights = lasso_cyclical_coordinate_descent(
    normalized_simple_feature_matrix, output, initial_weights, l1_penalty, tolerance)

In [244]:
[round(w) for w in weights]

[21624998.0, 63157247.0, 0.0]

In [245]:
def rss(feature_matrix, output, weights):
    return sum((output - predict_output(feature_matrix, weights))**2)

***QUIZ QUESTIONS***
1. What is the RSS of the learned model on the normalized dataset?
2. Which features had weight zero at convergence?

In [247]:
"%.2g" % rss(normalized_simple_feature_matrix, output, weights)

'1.6e+15'

## Evaluating LASSO fit with more features

Let us split the sales dataset into training and test sets.

In [195]:
train_data, test_data = sales.random_split(.8,seed=0)

Let us consider the following set of features.

In [196]:
all_features = ['bedrooms',
                'bathrooms',
                'sqft_living',
                'sqft_lot',
                'floors',
                'waterfront', 
                'view', 
                'condition', 
                'grade',
                'sqft_above',
                'sqft_basement',
                'yr_built', 
                'yr_renovated']

First, create a normalized feature matrix from the TRAINING data with these features.  (Make you store the norms for the normalization, since we'll use them later)

In [197]:
(feature_matrix, output) = get_numpy_data(train_data, all_features, my_output)
(normalized_feature_matrix, norms) = normalize_features(feature_matrix) 

First, learn the weights with `l1_penalty=1e7`, on the training data. Initialize weights to all zeros, and set the `tolerance=1`.  Call resulting weights `weights1e7`, you will need them later.

In [198]:
initial_weights = np.zeros(len(all_features)+1)

In [199]:
weights1e7 = lasso_cyclical_coordinate_descent(
    normalized_feature_matrix, output, initial_weights, l1_penalty=1e7)

***QUIZ QUESTION***

What features had non-zero weight in this case?

In [200]:
SFrame({'feature': ['intercept']+all_features, "weight": weights1e7})

Columns:
	feature	str
	weight	float

Rows: 14

Data:
+-------------+---------------+
|   feature   |     weight    |
+-------------+---------------+
|  intercept  | 24429600.2344 |
|   bedrooms  |      0.0      |
|  bathrooms  |      0.0      |
| sqft_living | 48389174.7715 |
|   sqft_lot  |      0.0      |
|    floors   |      0.0      |
|  waterfront | 3317511.21492 |
|     view    | 7329961.81171 |
|  condition  |      0.0      |
|    grade    |      0.0      |
+-------------+---------------+
[14 rows x 2 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

Next, learn the weights with `l1_penalty=1e8`, on the training data. Initialize weights to all zeros, and set the `tolerance=1`.  Call resulting weights `weights1e8`, you will need them later.

In [201]:
weights1e8 = lasso_cyclical_coordinate_descent(
    normalized_feature_matrix, output, initial_weights, l1_penalty=1e8)

***QUIZ QUESTION***

What features had non-zero weight in this case?

In [202]:
SFrame({'feature': ['intercept']+all_features, "weight": weights1e8})

Columns:
	feature	str
	weight	float

Rows: 14

Data:
+-------------+---------------+
|   feature   |     weight    |
+-------------+---------------+
|  intercept  | 71114625.7149 |
|   bedrooms  |      0.0      |
|  bathrooms  |      0.0      |
| sqft_living |      0.0      |
|   sqft_lot  |      0.0      |
|    floors   |      0.0      |
|  waterfront |      0.0      |
|     view    |      0.0      |
|  condition  |      0.0      |
|    grade    |      0.0      |
+-------------+---------------+
[14 rows x 2 columns]
Note: Only the head of the SFrame is printed.
You can use print_rows(num_rows=m, num_columns=n) to print more rows and columns.

Finally, learn the weights with `l1_penalty=1e4`, on the training data. Initialize weights to all zeros, and set the `tolerance=5e5`.  Call resulting weights `weights1e4`, you will need them later.  (This case will take quite a bit longer to converge than the others above.)

In [203]:
weights1e4 = lasso_cyclical_coordinate_descent(
    normalized_feature_matrix, output, initial_weights, l1_penalty=1e4, tolerance=5e5)

***QUIZ QUESTION***

What features had non-zero weight in this case?

In [249]:
SFrame({'feature': ['intercept']+all_features, "weighte7": weights1e7, "weighte8": weights1e8, "weighte4": weights1e4}).print_rows(20)

+---------------+----------------+---------------+---------------+
|    feature    |    weighte4    |    weighte7   |    weighte8   |
+---------------+----------------+---------------+---------------+
|   intercept   | 77779073.7862  | 24429600.2344 | 71114625.7149 |
|    bedrooms   | -22884012.0482 |      0.0      |      0.0      |
|   bathrooms   |  15348487.134  |      0.0      |      0.0      |
|  sqft_living  | 92166870.0204  | 48389174.7715 |      0.0      |
|    sqft_lot   | -2139328.02515 |      0.0      |      0.0      |
|     floors    | -8818455.59352 |      0.0      |      0.0      |
|   waterfront  | 6494209.78145  | 3317511.21492 |      0.0      |
|      view     | 7065161.89397  | 7329961.81171 |      0.0      |
|   condition   | 4119078.53917  |      0.0      |      0.0      |
|     grade     | 18436484.4859  |      0.0      |      0.0      |
|   sqft_above  | -14566678.7446 |      0.0      |      0.0      |
| sqft_basement | -5528348.9276  |      0.0      |      0.0   

## Rescaling learned weights

Recall that we normalized our feature matrix, before learning the weights.  To use these weights on a test set, we must normalize the test data in the same way.

Alternatively, we can rescale the learned weights to include the normalization, so we never have to worry about normalizing the test data: 

In this case, we must scale the resulting weights so that we can make predictions with *original* features:
 1. Store the norms of the original features to a vector called `norms`:
```
features, norms = normalize_features(features)
```
 2. Run Lasso on the normalized features and obtain a `weights` vector
 3. Compute the weights for the original features by performing element-wise division, i.e.
```
weights_normalized = weights / norms
```
Now, we can apply `weights_normalized` to the test data, without normalizing it!

Create a normalized version of each of the weights learned above. (`weights1e4`, `weights1e7`, `weights1e8`).

In [205]:
normalized_weights1e7 = weights1e7/norms
normalized_weights1e8 = weights1e8/norms
normalized_weights1e4 = weights1e4/norms

To check your results, if you call `normalized_weights1e7` the normalized version of `weights1e7`, then:
```
print normalized_weights1e7[3]
```
should return 161.31745624837794.

In [206]:
normalized_weights1e7[3]

161.31745764611762

## Evaluating each of the learned models on the test data

Let's now evaluate the three models on the test data:

In [250]:
(test_feature_matrix, test_output) = get_numpy_data(test_data, all_features, 'price')

Compute the RSS of each of the three normalized weights on the (unnormalized) `test_feature_matrix`:

In [255]:
"%.2g" % rss(test_feature_matrix, test_output, normalized_weights1e7)

'2.8e+14'

In [256]:
"%.2g" % rss(test_feature_matrix, test_output, normalized_weights1e8)

'5.4e+14'

In [257]:
"%.2g" % rss(test_feature_matrix, test_output, normalized_weights1e4)

'2.3e+14'

***QUIZ QUESTION***

Which model performed best on the test data?